### PR TITLE
feature/gap_analysis-issue23

### PR DESCRIPTION
**Pull request by nateagarwal**
This PR addresses Issue #23.

Here I have updated the turbine gross energy method to -25 compliant scada fields.
I've also modified the power_to_energy function in the unit conversion toolkit to use datetime frequency parameters instead of the integers. This allows us to directly pass the time frequency attributes for each object initially defined in the prepare script.

### CODE REVIEW

**Comment by moptis** [comment]
@nateagarwal  You are currently trying to merge into master. Please update the PR to merge to the develop branch.

**Comment by nateagarwal** [comment]
@moptis The PR has been updated to now merge to the develop branch

**Comment by moptis** [comment]
@nateagarwal  Thanks. It looks like it's trying to add the gap analysis method and the example notebook as new files. Strange since they should already be part of NREL/develop. Your fork and branch is up to date with NREL/develop, correct?

**Comment by moptis** [comment]
@nateagarwal Oh wait, nevermind. That gap analysis work got removed from NREL/develop because of that failed test. I"ll work on that now.,

**Comment by moptis** [comment]
@nateagarwal  I just merged the gap analysis back into NREL/develop. Can you resubmit this PR? I see it trying to add a lot of new files that it shouldn't. There should only be a few changes.

**Pull request merged**
