### PR TITLE
#17 Add the ENGIE open data wind farm to the examples

### PR DESCRIPTION
**Pull request by sebastianpfaffel**
#17 

I added the possibility to create turbine objects based on the ENGIE open data wind farm in the examples. An example was added to the ipnb as well. I had to fix some other minor issues on the ipnb as well to make it work. 

- print ("xyz") instead of print "xyz", Python 2.x vs. Python 3.x
- gam(...) instead of spline(....), the spline function has been renamed or deleted?

### CODE REVIEW

**Comment by jordanperr** [comment]
@moptis and @nateagarwal are updating turbine_gross_energy and the turbine example project to use -25 column names. I am waiting to merge in their pull request #28 before updating this one to reflect the new column names. Aside from this small change then PR looks good to me.

**Comment by sebastianpfaffel** [comment]
@jordanperr Thanks for your feedback. Let me know if there is anything else I can do or if any further changes are needed.

**Comment by jordanperr** [comment]
I've initiated a pull request into your develop branch. Please review my changes and merge them at your convenience. Once that is merged - I will be comfortable merging this PR into develop.

**Comment by sebastianpfaffel** [comment]
Thanks for the PR. It makes sense to split the examples and I merged it. Next time I'll make use of a separate branch for that issue again, kinda missed ... ;)  Do we need to change the docs to consider both examples now? Changes could be done in #29.

**Comment by jordanperr** [comment]
Yeah - I think it'd be better to implement #29 so the notebook is automatically included in the documentation. Up to you, though. I'm fine either way. Not a big deal to have an extra example notebook that is not mentioned in the documentation for now.

**Pull request merged**
