### PR TITLE
Feature/citation improvement

### LINKED ISSUE #171: Include Citation Information in Documentation
Now that the JOSS publication is live we should include the citation in:
- [x] the README
- [x] About section on the GitHub page [instructions](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files)
- [x] the documentation

### PR DESCRIPTION
**Pull request by RHammond2**
Closes #171 

This adds the citation information for users to easily access and hopefully use when working with OpenOA.

This PR updates:
 - the GitHub sidebar
 - the project readme
 - the homepage for the documentation site

### CODE REVIEW

**Review by jordanperr — COMMENTED** [review]
This is a good addition. Is there a better way to include the citation and author list without copying it three times throughout the repository? For example, could the citation.cff file be ingested by Sphinx and then rendered automatically? I don't think it's worth spending more than 20 minutes trying to get this to work. But I can see the current method leading to different citations/author lists in different places over time.

**Comment by RHammond2** [comment]
@jordanperr, I was just taking a quick look into this one and I can't find anything on it. I assume this is because the citation file is a `ruby-cff` file, so wouldn't likely be compatible with ReStructured Text formats. I see how this could become an issue going forward, but maybe we try to figure out an easier reference management system when we get there. I'm not sure that GitHub supports more than one at this time anyway.

**Review by ejsimley — APPROVED** [review]
This is really nice Rob, and it's great to have the JOSS paper to cite when using OpenOA. The only downside I see is that it's harder to cite a specific version of OpenOA. Although the JOSS paper is much nicer to cite than the GitHub repo itself, citing the GitHub page allows the version number to be included (for example, the suggested [FLORIS citation](https://github.com/NREL/floris/tree/main#citation)). I wonder if/how we could cite a particular version of the code using JOSS.

Also, in the GH sidebar citation window, clicking on "View Citation File" doesn't seem to open anything for me. Is this supposed to do anything?

**Comment by jordanperr** [comment]
Closing and re-opening to trigger a new build. Hopefully the CI/CD will be fixed this time.

**Comment by jordanperr** [comment]
CI GBM issue has been fixed.

Docs are failing due to changes within this pull request. Happy to help debug this with you. I added .readthedocs.yaml file to the repo root which you can use to tweak readthedocs build settings.

**Pull request merged**
